export const siteConfig = {
    name: "XAR",
    description: "A custom made MAC based OS",
    url: "http://xar-os.vercel.app",
    ogImage: "http://xar-os.vercel.app/icon.jpg",
    keywords: [
        "DRVGO",
        "drago",
        "dragoluca",
        "sarthak kundu",
        "sarthak",
        "itsdrvgo",
        "XAR",
        "xar",
        "xaros",
        "xar-os",
    ],
    links: {
        youtube: "https://youtube.com/@itsdrvgo",
        instagram: "https://instagram.com/itsdrvgo",
        twitter: "https://www.twitter.com/itsdrvgo",
        github: "https://www.github.com/itsdrvgo",
        discord: "https://www.dsc.gg/drvgo",
        source: "https://github.com/itsdrvgo/xar-os",
    },
};
